### ISSUE TITLE
Реализовать пререлизную версию для презентации Мариусу

### ISSUE THREAD

**Issue by DjonnyX** [DjonnyX/intellistaff#50]
## Задачи по фронту:
- [ ] #51 Реализовать сценарии
- [ ] #52 Реализовать модификаторы
- [ ] #53 Реализовать порции
- [ ] #54 Добавить выбор типов заказа
- [ ] #55  Реализовать систему локализации
- [ ] #56 Реализовать нормальный cms
